[project]
name = "AirPred"
version = "1.0"
description = ""
authors = []
dependencies = [
    "tensorflow>=2.14.0",
    "pandas>=2.1.2",
    "scikit-learn>=1.3.2",
    "matplotlib>=3.8.1",
]
requires-python = ">=3.9, <3.10"
readme = "README.md"
license = {text = "MIT"}

